### ISSUE TITLE
Restore AppVeyor integration

### ISSUE THREAD

**Issue by abitrolly** [kinaklub/next.filmfest.by#141]
@nott or @davojta do you know who can reenable AppVeyor to make test pass in this repo?

https://help.appveyor.com/discussions/problems/28742-no-status-updates-on-github

**Comment by staaas** [comment]
![image](https://user-images.githubusercontent.com/382950/102718101-6f80cf00-42f7-11eb-9bfd-5a430fbad0ff.png)

@abitrolly appveyor was enabled, however it was recongnizing this as a MSBuild project.

Good news is that changing the configuration option above helped to make the project green again.
Bad news is that .appveyor.yml is not taken into account, so no tests are executed.

**Comment by abitrolly** [comment]
@nott AppVeyor can not checkout the code from GitHub, because credentials stored on AppVeyor side are invalid. That's why it can not access `appveyor.yml`. To fix this, you need to remove AppVeyor integration from this repo and add it again.

**Comment by abitrolly** [comment]
That's also the reason why failed status it not reported in PRs.

**Comment by abitrolly** [comment]
Hello @nott.

![image](https://user-images.githubusercontent.com/8781107/103266255-3ebc2c00-49c0-11eb-8944-85eafe94d162.png)

:D

**Comment by abitrolly** [comment]
@nott have you looked into removing and adding AppVeyor integration to this repo again? I don't want to break tests when upgrading dependencies.

**Comment by davojta** [comment]
@abitrolly I have removed the AppVeyor from integrations and grant you access to setup integration again. Could you accomplish your task?

**Comment by abitrolly** [comment]
@davojta no, I don't see **kinaklub** organization in https://github.com/marketplace/appveyor

**Comment by staaas** [comment]
![image](https://user-images.githubusercontent.com/382950/104436389-98b31900-559e-11eb-9579-4a6c0d4e5e91.png)

**Comment by staaas** [comment]
@abitrolly would you like to pair on this some time this week?

**Comment by abitrolly** [comment]
@nott yep, anytime is fine, except next 8 hours. )

**Comment by abitrolly** [comment]
AppVeyor takes so much time and I replaced it with GitHub Actions in #142.
