### ISSUE TITLE
move results/migrations/raw_data/2012_winners/ to /data/raw 

### ISSUE THREAD

**Issue by davojta** [kinaklub/next.filmfest.by#46]
from https://github.com/kinaklub/next.filmfest.by/pull/35/files

**Comment by davojta** [comment]
https://github.com/kinaklub/next.filmfest.by/pull/56

**Comment by abitrolly** [comment]
Done in https://github.com/kinaklub/next.filmfest.by/pull/56/commits/c579a713c4b912f532b1e8f807b8990bd62de836
