### ISSUE TITLE
Project Intro

### ISSUE THREAD

**Issue by davojta** [kinaklub/next.filmfest.by#51]
- join https://vector.im/beta/#/room/#cpm-dev:matrix.org
- take look on http://filmfest.by/be/ (markup, css, js, pages, images)
- look around https://github.com/kinaklub/next.filmfest.by and https://github.com/kinaklub/filmfest.by
- join https://github.com/kinaklub/

**Comment by sliveyourlifes** [comment]
https://github.com/sliveyourlifes

**Comment by abitrolly** [comment]
<img src="http://idolosol.com/images/what-3.jpg" width="400">

**Comment by davojta** [comment]
Everything is done )
