### ISSUE TITLE
Develop html markup for news page

### ISSUE THREAD

**Issue by davojta** [kinaklub/next.filmfest.by#52]
- news should contain title as link
- news should contain date
- news should contain category
- news should contain social links
- news should contain images (or stub image if article without image) 
- news should contain show more link if news is bigger then 2 sentences

See http://worldoftanks.com/ for reference

**Comment by davojta** [comment]
https://github.com/kinaklub/next.filmfest.by/pull/53

**Comment by sliveyourlifes** [comment]
done
