### ISSUE TITLE
Finish Bootstrap milestone

### ISSUE THREAD

**Issue by abitrolly** [kinaklub/next.filmfest.by#68]
https://github.com/kinaklub/next.filmfest.by/milestones

Import current festival results from http://filmfest.by/ to new Django model.

1. Export current data into JSON (fixtures)
* [x] #66 
2. Add Django models
* [x] moved to next milestone
3. Import data (through migrations)

* [x] films
* [x] jury members
* [x] partners

Bonus points:

- save pictures of data models (Django and JSON fixtures)

**Comment by davojta** [comment]
Export current data into JSON - will be done with https://github.com/kinaklub/next.filmfest.by/pull/66

django models will be moved to next milestone due to refactoring in migration utils and rework pages structure

import data - will be done after utils rework after @nott refactorings
