### ISSUE TITLE
deploy docker containers 

### ISSUE THREAD

**Issue by davojta** [kinaklub/next.filmfest.by#73]
from here  - https://github.com/kinaklub/docs/blob/master/MFU_2016_10_29.md

**Comment by abitrolly** [comment]
I am trying to build a list of containers used. They are located in https://github.com/kinaklub/next.filmfest.by/blob/master/Dockerfile, https://github.com/kinaklub/next.filmfest.by/blob/master/Dockerfile-nginx and in https://github.com/kinaklub/next.filmfest.by/blob/master/docker-compose.yml

images referenced:
-  fedora:24
-  nginx
-  image: postgres:latest
-  image: elasticsearch:1.7.3

**Comment by staaas** [comment]
Done in #100
