### ISSUE TITLE
deploy button 

### ISSUE THREAD

**Issue by davojta** [kinaklub/next.filmfest.by#74]
need to give access to deploy to every user with correct roles after successful tests proceeding

https://github.com/kinaklub/docs/blob/master/MFU_2016_10_29.md

**Comment by staaas** [comment]
After #100 is merged, we deploy each time a commit to master is pushed (it usually happens on PR merge).

One can also restart the deploy at https://travis-ci.org/kinaklub/next.filmfest.by
