### ISSUE TITLE
Setup Netlify for content previews

### ISSUE THREAD

**Issue by abitrolly** [kinaklub/next.filmfest.by#78]
Pro plan free for open source projects - https://www.netlify.com/pricing/ - which is [what we are](https://github.com/kinaklub/next.filmfest.by/blob/master/UNLICENSE).

**Comment by abitrolly** [comment]
Done - https://app.netlify.com/sites/filmfest

Added @davojta to collaborators, need more emails from @all to add access too.

Permissions are needed for Netlify to deploy its hooks.

**Comment by staaas** [comment]
@abitrolly 

Personally I don't see we need a CDN these days, so I'd prefer to keep it simple.

Are there any benefits of using netlify I should know about? Or did you have I consensus on this in a group?

**Comment by abitrolly** [comment]
@nott this is needed to preview PRs. We haven't setup hosting for next, so I've chosen Netlify for now. I need to test deployment scripts somewhere.

**Comment by davojta** [comment]
linked to https://github.com/kinaklub/next.filmfest.by/issues/73
and https://github.com/kinaklub/next.filmfest.by/issues/74

**Comment by davojta** [comment]
@abitrolly my account is not linked to the project. I think because i use private email for github not public one. 

Please give access again and to damarah@gmail.com too

**Comment by davojta** [comment]
@abitrolly seems that netlify is for static generated websites, isnt it ?

**Comment by abitrolly** [comment]
Yes. But previews are available endlessly. Can you still enable Netlify for this repo? I need it to build for my PRs to test the technology.

**Comment by staaas** [comment]
@abitrolly I've enabled it a couple of days ago.

**Comment by abitrolly** [comment]
@nott I don't see checks in https://github.com/kinaklub/next.filmfest.by/pull/76 - will recheck Netlify setup later today.

**Comment by staaas** [comment]
@abitrolly you now have admin permissions for this repo.

**Comment by abitrolly** [comment]
Done with hook installation. The problem was that it was installed for my clone @abitrolly.

**Comment by abitrolly** [comment]
For future reference https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/
